export const QUERY_KEYS = {
  USER_PROFILE: 'USER_PROFILE',
  USER_COMMENTS: 'USER_COMMENTS',
  QUESTIONS: 'QUESTIONS',
  COMMENTS: 'COMMENTS',
  USER_ANSWERS: 'USER_ANSWERS',
  EXERCISE: 'EXERCISE',
  RANDOM_QUESTIONS: 'RANDOM_QUESTIONS',
  SUBSCRIPTION: 'SUBSCRIPTION',
  QUOTA: 'QUOTA',
  PAPER_NAME_MAPPING: 'PAPER_NAME_MAPPING',
  MESSAGES: 'MESSAGES',
  RANKING: 'RANKING',
};

export const CMS_QUERY_KEYS = {
  CMS_USERS: 'CMS_USERS',
  CMS_COMMENTS: 'CMS_COMMENTS',
  CMS_QUESTIONS: 'CMS_QUESTIONS',
  CMS_EXERCISE: 'CMS_EXERCISE',
  CMS_PAYMENT: 'CMS_PAYMENT',
  CMS_SUBSCRIPTION: 'CMS_SUBSCRIPTION',
  CMS_QUOTA: 'CMS_QUOTA',
};

export const QUESTION_DIFFICULTY_THRESHOLD = {
  EASY: 70,
  HARD: 48,
  EXTREME_HARD: 35,
};

export const FREE_USER_QUOTA = {
  EXPORT_PDF_QUOTA_DAILY: 3,
  MAXIMUM_DISPLAY_SELECT_ITEMS: 20,
};

export enum LanguageEnum {
  TC = 'tc',
  EN = 'en',
}

export const webData = {
  title: 'DSE00 exam',
  slogen: '一站式操卷工具',
  description: '準備 DSE 考試的操卷網站',
  icons: ['/favicon.ico'],
};

export const COOKIES_KEY = {
  LAST_QUESTION: 'lastQuestion',
  TOKEN: 'token',
};
