export const QUERY_KEYS = {
  USER_PROFILE: 'USER_PROFILE',
  USER_COMMENTS: 'USER_COMMENTS',
  QUESTIONS: 'QUESTIONS',
  COMMENTS: 'COMMENTS',
  USER_ANSWERS: 'USER_ANSWERS',
  EXERCISE: 'EXERCISE',
  RANDOM_QUESTIONS: 'RANDOM_QUESTIONS',
  SUBSCRIPTION: 'SUBSCRIPTION',
};

export const QUESTION_DIFFICULTY_THRESHOLD = {
  EASY: 70,
  HARD: 45,
  EXTREME_HARD: 30,
};
