import type { Metadata } from "next";
import "./globals.css";
import RootProvider from "@/providers/root";
import LayoutProvider from "@/providers/LayoutProvider";

export const metadata: Metadata = {
  title: "DSE00 Exam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          <LayoutProvider>
            {children}
          </LayoutProvider>
        </RootProvider>
      </body>
    </html>
  );
}

