import type { Metadata } from "next";
import "./globals.css";
import BaseWebProvider from "@/providers/baseWebProvider";
import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <BaseWebProvider>
          <div className="container py-12">{children}</div>
        </BaseWebProvider>
      </body>
    </html>
  );
}
