import type { Metadata } from "next";
import "./globals.css";
import RootProvider from "@/providers/root";

import Header from "./_components/Header";

export const metadata: Metadata = {
  title: "DSE00 Exam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootProvider>
          <div className="flex flex-col items-center">
            <Header />
            <div className="container justify-center py-12">{children}</div>
          </div>
        </RootProvider>
      </body>
    </html>
  );
}

